### PR TITLE
Feature/user service

### PR DESCRIPTION
**Pull request by MonicaNS**
-Need to build up the jar file first
- Syntax to run the main from jar file is as follows:
 java -jar path/to/your/jarfile.jar fully.qualified.package.Application

### CODE REVIEW

**Comment by bubblemans** [comment]
steps to run spring-boot with maven on Mac:

1. brew install springboot
2. brew install maven
3. mvn spring-boot:run

**Comment by bubblemans** [comment]
Please remove all .DS_STORE files.

**Comment by bubblemans** [comment]
- Add getUserByToken
- Add generateToken

**Comment by MonicaNS** [comment]
To test the new method (getIdByToken()) using postman:
Enter a random user Id and a given token to the path of a GET request to receive the actual expected user Id. 

Example:
URI: http://localhost:8080/api/users/16/token?token=cfcd208495d565ef66e7dff9f98764da
In the path above 16 represents the random user ID and the value after the equal sign is the given token.

Response for above would include a JSON object like below:
{
 "user Id" : "17"
}

**Comment by bubblemans** [comment]
Good job!

A few things to include in your next PR:
1. What happens if two people input the same information when signing up? (duplicate entities)
2. Remove the lines you commented out.

If you have more time:
1. make id and token as request variables so that they can be accessed like "api/users?token=cfcd208495d565ef66e7dff9f98764da" and "api/users?id=1"

**Review by bubblemans — APPROVED** [review]

**Pull request merged**
