### PR TITLE
added course apis

### PR DESCRIPTION
**Pull request by GyohoWu**
created tables and all APIs about the course features.

### CODE REVIEW

**Comment by GyohoWu** [comment]
deleted some columns of student and instructor entity.
made new function on courseController to get sections by course name, semester, and year

**Comment by bubblemans** [comment]
delete DS_STORE file

**Comment by bubblemans** [comment]
Include how you test your endpoints using Postman.
And list out the endpoints we need for the sprint 4 demo.

**Comment by GyohoWu** [comment]
changes made:
1. HttpRequest
2. getSectionBySemYear
3. createStudent
4. createStudent
5. createTakes
6. getGradesByStudent
7. .DS_Store deleted
8. added .gitignore

Test screenshots:
https://docs.google.com/document/d/1VKScl8g7njhSyrdNmKLjs5fLMoUitt2zWT09eXu37qM/edit
backend API document:
https://docs.google.com/document/d/1dlW9OWzSsp9zRYAq_hr11200KZfORqU_tUmzWm-IzuA/edit

**Review by bubblemans — APPROVED** [review]

**Review by MonicaNS — COMMENTED** [review]
-Remove the commented code next time
-Watch your indentations and extra lines for better readability

**Pull request merged**
